# MUST use Debian Bullseye (Python 3.9). Ryu breaks on Python 3.10+ due to
# an eventlet/TimeoutError compatibility bug.
FROM debian:bullseye-slim
ARG DEBIAN_FRONTEND="noninteractive"
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip python3-setuptools python3-dev gcc \
    iproute2 iputils-ping && rm -rf /var/lib/apt/lists/*
RUN ln -sf /usr/bin/python3 /usr/bin/python
RUN ln -sf /usr/bin/pip3 /usr/bin/pip
RUN pip install "eventlet==0.30.2"
RUN pip install "oslo.config==5.2.1"
RUN pip install ryu --no-build-isolation
WORKDIR /
