score[0]="CTRL"
score[1]="CORE_S1"
score[2]="CORE_S2"
score[3]="CORE_S3"
score[image]="kathara/sdn"

s1[0]="CTRL"
s1[1]="CORE_S1"
s1[2]="S1_H1"
s1[3]="S1_H2"
s1[image]="kathara/sdn"

s2[0]="CTRL"
s2[1]="CORE_S2"
s2[2]="S2_H3"
s2[3]="S2_H4"
s2[image]="kathara/sdn"

s3[0]="CTRL"
s3[1]="CORE_S3"
s3[2]="S3_H5"
s3[3]="S3_H6"
s3[image]="kathara/sdn"

controller[0]="CTRL"
controller[image]="custom/ryu"
controller[bridged]=true
controller[port]="8080:8080/tcp"
controller[num_terms]=0

h1[0]="S1_H1/00:00:00:00:00:01"
h1[image]="kathara/base"
h1[num_terms]=0
h2[0]="S1_H2/00:00:00:00:00:02"
h2[image]="kathara/base"
h2[num_terms]=0
h3[0]="S2_H3/00:00:00:00:00:03"
h3[image]="kathara/base"
h3[num_terms]=0
h4[0]="S2_H4/00:00:00:00:00:04"
h4[image]="kathara/base"
h4[num_terms]=0
h5[0]="S3_H5/00:00:00:00:00:05"
h5[image]="kathara/base"
h5[num_terms]=0
h6[0]="S3_H6/00:00:00:00:00:06"
h6[image]="kathara/base"
h6[num_terms]=0
